"use strict";
/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Quickstart API Reference
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases.

To use the Quickstart API, you must have the following features enabled on your tenant:
 
* [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization)
* [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)

To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/).
We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.


 * OpenAPI spec version: 2024-01-24
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.RefundPaymentMethodType = void 0;
/**
 * The type of the payment method. An additional hash is included on the payment method with a name matching this value. It contains additional information specific to the payment method type.
 */
var RefundPaymentMethodType;
(function (RefundPaymentMethodType) {
    RefundPaymentMethodType["paypal_express"] = "paypal_express";
    RefundPaymentMethodType["paypal_express_native"] = "paypal_express_native";
    RefundPaymentMethodType["paypal_adaptive"] = "paypal_adaptive";
    RefundPaymentMethodType["card"] = "card";
    RefundPaymentMethodType["cc_ref"] = "cc_ref";
    RefundPaymentMethodType["ach_debit"] = "ach_debit";
    RefundPaymentMethodType["sepa_debit"] = "sepa_debit";
    RefundPaymentMethodType["betalings_debit"] = "betalings_debit";
    RefundPaymentMethodType["autogiro_debit"] = "autogiro_debit";
    RefundPaymentMethodType["bacs_debit"] = "bacs_debit";
    RefundPaymentMethodType["au_becs_debit"] = "au_becs_debit";
    RefundPaymentMethodType["nz_becs_debit"] = "nz_becs_debit";
    RefundPaymentMethodType["pad_debit"] = "pad_debit";
    RefundPaymentMethodType["apple_pay"] = "apple_pay";
    RefundPaymentMethodType["wire_transfer"] = "wire_transfer";
    RefundPaymentMethodType["check"] = "check";
    RefundPaymentMethodType["cash"] = "cash";
    RefundPaymentMethodType["other"] = "other";
    RefundPaymentMethodType["paypal"] = "paypal";
    RefundPaymentMethodType["adyen_google_pay"] = "adyen_google_pay";
    RefundPaymentMethodType["adyen_apple_pay"] = "adyen_apple_pay";
})(RefundPaymentMethodType || (exports.RefundPaymentMethodType = RefundPaymentMethodType = {}));
