/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Quickstart API Reference
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases.

To use the Quickstart API, you must have the following features enabled on your tenant:
 
* [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization)
* [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)

To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/).
We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.


 * OpenAPI spec version: 2024-01-24
 */
/**
 * Specifies on which day or the month or day of the week a customer shall be billed.
 * @deprecated
 */
export var RecurringOn;
(function (RecurringOn) {
    RecurringOn["_1"] = "_1";
    RecurringOn["_2"] = "_2";
    RecurringOn["_3"] = "_3";
    RecurringOn["_4"] = "_4";
    RecurringOn["_5"] = "_5";
    RecurringOn["_6"] = "_6";
    RecurringOn["_7"] = "_7";
    RecurringOn["_8"] = "_8";
    RecurringOn["_9"] = "_9";
    RecurringOn["_10"] = "_10";
    RecurringOn["_11"] = "_11";
    RecurringOn["_12"] = "_12";
    RecurringOn["_13"] = "_13";
    RecurringOn["_14"] = "_14";
    RecurringOn["_15"] = "_15";
    RecurringOn["_16"] = "_16";
    RecurringOn["_17"] = "_17";
    RecurringOn["_18"] = "_18";
    RecurringOn["_19"] = "_19";
    RecurringOn["_20"] = "_20";
    RecurringOn["_21"] = "_21";
    RecurringOn["_22"] = "_22";
    RecurringOn["_23"] = "_23";
    RecurringOn["_24"] = "_24";
    RecurringOn["_25"] = "_25";
    RecurringOn["_26"] = "_26";
    RecurringOn["_27"] = "_27";
    RecurringOn["_28"] = "_28";
    RecurringOn["_29"] = "_29";
    RecurringOn["_30"] = "_30";
    RecurringOn["_31"] = "_31";
    RecurringOn["subscription_item_start_day"] = "subscription_item_start_day";
    RecurringOn["account_cycle_date"] = "account_cycle_date";
    RecurringOn["subscription_start_day"] = "subscription_start_day";
    RecurringOn["term_end_day"] = "term_end_day";
    RecurringOn["monday"] = "monday";
    RecurringOn["tuesday"] = "tuesday";
    RecurringOn["wednesday"] = "wednesday";
    RecurringOn["thursday"] = "thursday";
    RecurringOn["friday"] = "friday";
    RecurringOn["saturday"] = "saturday";
    RecurringOn["sunday"] = "sunday";
})(RecurringOn || (RecurringOn = {}));
