/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Quickstart API Reference
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases.

To use the Quickstart API, you must have the following features enabled on your tenant:
 
* [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization)
* [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)

To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/).
We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.


 * OpenAPI spec version: 2024-01-24
 */
import type { Account } from './account';
import type { ArTransactionsOrders } from './arTransactionsOrders';
import type { OrderCancelResponseCategory } from './orderCancelResponseCategory';
import type { OrderCancelResponseCustomFields } from './orderCancelResponseCustomFields';
import type { OrderCancelResponseCustomObjects } from './orderCancelResponseCustomObjects';
import type { OrderCancelResponseLineItems } from './orderCancelResponseLineItems';
import type { OrderCancelResponseState } from './orderCancelResponseState';
import type { PostSubscriptionOrderResponse } from './postSubscriptionOrderResponse';
import type { WriteOff } from './writeOff';
/**
 */
export interface OrderCancelResponse {
    /** Information of the new account associated with the subscription. */
    account?: Account;
    /** Identifier of the account associated with this subscription. */
    account_id?: string;
    ar_transactions?: ArTransactionsOrders;
    /** Category of the order to indicate a product sale or return. Default value is `sale`. */
    category?: OrderCancelResponseCategory;
    /** Unique identifier of the Zuora user who created the object */
    readonly created_by_id?: string;
    /** The date and time when the object was created in ISO 8601 UTC format. */
    readonly created_time?: Date;
    /** Set of user-defined fields associated with this object. Useful for storing additional information about the object in a structured format. */
    custom_fields?: OrderCancelResponseCustomFields;
    /** The custom objects associated with a Zuora standard object. */
    readonly custom_objects?: OrderCancelResponseCustomObjects;
    /** An arbitrary string attached to the object. Often useful for displaying to users. */
    description?: string;
    /** Unique identifier for the object. */
    readonly id?: string;
    /** */
    line_items?: OrderCancelResponseLineItems;
    /** The date when the order is signed. All the order actions under this order will use this order date as the contract effective date if the contract effective date field is skipped or its value is left as null. */
    order_date?: Date;
    /** The order number of the new order. If not provided, system will auto-generate a number for this order.     Note: Ensure that the order number does not contain a slash. */
    order_number?: string;
    /** The status of the order. */
    state?: OrderCancelResponseState;
    /** Each item includes specific fields based on the intended order action. */
    subscriptions?: PostSubscriptionOrderResponse[];
    /** Unique identifier of the Zuora user who last updated the object */
    readonly updated_by_id?: string;
    /** The date and time when the object was last updated in ISO 8601 UTC format. */
    readonly updated_time?: Date;
    /** The billing documents that are written off. */
    write_offs?: WriteOff[];
}
