/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Quickstart API Reference
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases.

To use the Quickstart API, you must have the following features enabled on your tenant:
 
* [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization)
* [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)

To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/).
We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.


 * OpenAPI spec version: 2024-01-24
 */
import type { PaymentScheduleBillingDocumentRequest } from './paymentScheduleBillingDocumentRequest';
import type { CustomFields } from './customFields';
import type { PaymentScheduleItemRequest } from './paymentScheduleItemRequest';
import type { PaymentSchedulePaymentOptionRequest } from './paymentSchedulePaymentOptionRequest';
import type { PaymentScheduleCreateRequestPeriod } from './paymentScheduleCreateRequestPeriod';
/**
 */
export interface PaymentScheduleCreateRequest {
    /** Unique identifier of the customer account the payment schedule belongs to. */
    account_id?: string;
    /** Account number of the customer account the payment schedule belongs to. */
    account_number?: string;
    /** The amount of each payment schedule item in the payment schedule. */
    amount?: number;
    /** The billing document with which the payment schedule is associated. Note: This field is optional. If you have the Standalone Payment feature enabled, you can leave this field blank and set standalone to true to create standalone payments. You can also choose to create unapplied payments by leaving this object blank and setting standalone to false. If Standalone Payment is not enabled, leaving this object unspecified will create unapplied payments. */
    billing_document?: PaymentScheduleBillingDocumentRequest;
    /** Currency of the payment schedule. Note: This field is optional. The default value is the account's default currency. This field will be ignored when items is specified. */
    currency?: string;
    custom_fields?: CustomFields;
    /** An arbitrary string attached to the object. Often useful for displaying to users. */
    description?: string;
    /** Container for payment schedule items. */
    items?: PaymentScheduleItemRequest[];
    /** The number of payment schedule items to be created for this payment schedule. */
    number_of_payments?: number;
    /** ID of the payment gateway used to collect payments. Note: This field is optional. The default value is the account's default payment gateway ID. If no payment gateway ID is found on the customer account level, the default value will be the tenant's default payment gateway ID. This field will be ignored when items is specified. */
    payment_gateway_id?: string;
    /** The payment gateway number of the payment gateway used to collect scheduled payments. */
    payment_gateway_number?: string;
    /** ID of the payment method. Note: This field is optional. The default value is the account's default payment method ID. This field will be ignored when items is specified. */
    payment_method_id?: string;
    /** The payment method number of the payment method to be used to collect payments. */
    payment_method_number?: string;
    /** Container for the payment options, which describe the transactional level rules for processing payments. Currently, only the gateway_options type is supported. Payment schedule payment_options take precedence over payment schedule item payment_options. */
    payment_options?: PaymentSchedulePaymentOptionRequest[];
    /** Number of the payment schedule. */
    payment_schedule_number?: string;
    /** Unit in which term duration is defined. One of week or month. */
    period?: PaymentScheduleCreateRequestPeriod;
    /** Indicates whether the payments created by the payment schedule will be used as reserved payments. This field will only be available if the prepaid cash drawdown permission is enabled. See <a href="https://knowledgecenter.zuora.com/Zuora_Billing/Bill_your_customers/Bill_for_usage_or_prepaid_products/Advanced_Consumption_Billing/Prepaid_with_Drawdown" target="_blank">Prepaid Cash with Drawdown for more information.</a> */
    prepayment?: boolean;
    /** Indicates whether the payments created by the payment schedule are standalone payments or not.
        When setting to `true`, standalone payments will be created.       When setting to `false`, you can either specify a billing document, or not specifying any billing documents.       In the latter case, unapplied payments will be created.       If set to `null`, standalone payments will be created.
        **Note**: This parameter is only available if standalone payments are enabled in your tenant. The default value is `true` if standalone payments are enabled in your tenant. */
    standalone?: boolean;
    /** The date of the first scheduled payment collection. Note: This parameter is required when `items` is not specified. This parameter will be ignored when `items` is specified. */
    start_date?: Date;
    /** The total amount to be collected by the payment schedule. */
    total_amount?: number;
}
