/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Quickstart API Reference
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases.

To use the Quickstart API, you must have the following features enabled on your tenant:
 
* [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization)
* [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)

To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/).
We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.


 * OpenAPI spec version: 2024-01-24
 */
/**
 */
export interface PaymentRunSummary {
    /** The total number of all receivables with payments not processed. */
    errors_total?: number;
    /** The total number of all invoices. */
    invoices_total?: number;
    /** The number of credit memos processed. */
    number_of_credit_memos?: number;
    /** The number of debit memos processed. */
    number_of_debit_memos?: number;
    /** The number of payments not processed. */
    number_of_errors?: number;
    /** The number of invoices processed. */
    number_of_invoices?: number;
    /** The number of payments processed. */
    number_of_payments?: number;
    /** The number of unapplied payments. */
    number_of_unapplied_payments?: number;
    /** The number of unprocessed debit memos. */
    number_of_unprocessed_debit_memos?: number;
    /** The number of receivables with positive remamining balances. */
    number_of_unprocessed_receivables?: number;
    /** The total number of all processed and unapplied payments. */
    payments_total?: number;
    /** The total number of positive remaining balances of all receivables. */
    unprocessed_receivables_total?: number;
}
