/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Quickstart API Reference
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases.

To use the Quickstart API, you must have the following features enabled on your tenant:
 
* [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization)
* [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)

To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/).
We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.


 * OpenAPI spec version: 2024-01-24
 */
import type { PaymentScheduleBillingDocumentResponse } from './paymentScheduleBillingDocumentResponse';
import type { PaymentScheduleItemCustomFields } from './paymentScheduleItemCustomFields';
import type { PaymentScheduleItemCustomObjects } from './paymentScheduleItemCustomObjects';
import type { Payment } from './payment';
import type { PaymentSchedule } from './paymentSchedule';
import type { PaymentScheduleItemPayments } from './paymentScheduleItemPayments';
import type { PaymentScheduleItemState } from './paymentScheduleItemState';
/**
 */
export interface PaymentScheduleItem {
    /** Unique identifier of the customer account the payment schedule belongs to. */
    account_id?: string;
    /** The amount to be collected by this payment schedule item. */
    amount?: number;
    /** The remaining balance of payment schedule item. */
    balance?: number;
    /** The billing document with which the payment schedule is associated. If you have the Standalone Payment feature enabled, you can leave this field blank and set standalone to true to create standalone payments. You can also choose to create unapplied payments by leaving this object blank and setting standalone to false. If Standalone Payment is not enabled, leaving this object unspecified will create unapplied payments. */
    billing_document?: PaymentScheduleBillingDocumentResponse;
    /** The reason for the cancellation of payment schedule item. */
    cancellation_reason?: string;
    /** Unique identifier of the Zuora user who created the object */
    readonly created_by_id?: string;
    /** The date and time when the object was created in ISO 8601 UTC format. */
    readonly created_time?: Date;
    /** Currency of the payment schedule. The default value is the account's default currency. This field will be ignored when items is specified. */
    currency?: string;
    /** Set of user-defined fields associated with this object. Useful for storing additional information about the object in a structured format. */
    custom_fields?: PaymentScheduleItemCustomFields;
    /** The custom objects associated with a Zuora standard object. */
    readonly custom_objects?: PaymentScheduleItemCustomObjects;
    /** An arbitrary string attached to the object. Often useful for displaying to users. */
    description?: string;
    /** An error message indicating why payment collection failed for this payment schedule item. */
    error_message?: string;
    /** Unique identifier for the object. */
    readonly id?: string;
    /** List of customer payments. */
    readonly payment?: Payment;
    /** ID of the payment gateway used to collect payments. The default value is the account's default payment gateway ID. If no payment gateway ID is found on the customer account level, the default value will be the tenant's default payment gateway ID. This field will be ignored when `items` is specified. */
    payment_gateway_id?: string;
    /** ID of the payment method. The default value is the account's default payment method ID. This field will be ignored when `items` is specified. */
    payment_method_id?: string;
    /** ID of the payment option. */
    payment_option_id?: string;
    /** Payment schedule record. */
    readonly payment_schedule?: PaymentSchedule;
    /** ID of the payment schedule. */
    payment_schedule_id?: string;
    /** Number of the payment schedule item. */
    payment_schedule_item_number?: string;
    /** Number of the payment schedule. */
    payment_schedule_number?: string;
    payments?: PaymentScheduleItemPayments[];
    /**
     * At which hour in the day in the tenant's timezone this payment will be collected. Available values:[0,1,2,~,22,23]. If the time difference between your tenant’s timezone and the timezone where Zuora servers are located is not in full hours, for example, 2.5 hours, the payment schedule items will be triggered half an hour later than your scheduled time. The default value is 0. If the payment run_hour and scheduled_date are backdated, the system will collect the payment when the next run_hour occurs.
     * @minimum 0
     * @maximum 23
     */
    run_hour?: number;
    /** The scheduled date of collection. */
    scheduled_date?: Date;
    /** Indicates whether the payments created by the payment schedule are standalone payments or not. When setting to true, standalone payments will be created. When setting to false, you can either specify a billing document, or not specifying any billing documents. In the later case, unapplied payments will be created. If set to null, standalone payments will be created. Note: This parameter is only available if standalone payments are enabled in your tenant. Do not include this parameter if standalone payment have not been enabled in your tenant. If standalone payments are enabled, the default value is true. */
    standalone?: boolean;
    /** The status of the payment schedule item. active: there are unprocessed payment schedule items. canceled: the payment schedule has been canceled. complete: the payment schedule is complete and all items have been processed. */
    state?: PaymentScheduleItemState;
    /** Unique identifier of the Zuora user who last updated the object */
    readonly updated_by_id?: string;
    /** The date and time when the object was last updated in ISO 8601 UTC format. */
    readonly updated_time?: Date;
}
