/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Quickstart API Reference
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases.

To use the Quickstart API, you must have the following features enabled on your tenant:
 
* [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization)
* [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)

To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/).
We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.


 * OpenAPI spec version: 2024-01-24
 */
import type { PaymentRunCustomFields } from './paymentRunCustomFields';
import type { PaymentRunCustomObjects } from './paymentRunCustomObjects';
import type { PaymentRunState } from './paymentRunState';
import type { PaymentRunStateTransitionsAllOf } from './paymentRunStateTransitionsAllOf';
import type { PaymentRunSummary } from './paymentRunSummary';
/**
 */
export interface PaymentRun {
    /** If true, any posted credit memos are applied first. */
    apply_credit_memos?: boolean;
    /** If true, any unapplied payments are applied first. */
    apply_unapplied_payments?: boolean;
    /** Identifier of the customer account batch to be included in this payment run. */
    batch?: string;
    /**
     * The day of the month to bill multiple customer accounts.
     * @minimum 0
     * @maximum 31
     */
    bill_cycle_day?: number;
    /** The unique identifier of a bill run. */
    bill_run_id?: string;
    /** Indicates whether to process electronic payments during the execution of payment runs. */
    collect_payment?: boolean;
    /** If true, a single payment will be collected for all receivables due on an account. */
    consolidate_payment?: boolean;
    /** Unique identifier of the Zuora user who created the object */
    readonly created_by_id?: string;
    /** The date and time when the object was created in ISO 8601 UTC format. */
    readonly created_time?: Date;
    /** Three-letter ISO currency code. */
    currency?: string;
    /** Set of user-defined fields associated with this object. Useful for storing additional information about the object in a structured format. */
    custom_fields?: PaymentRunCustomFields;
    /** The custom objects associated with a Zuora standard object. */
    readonly custom_objects?: PaymentRunCustomObjects;
    /** Unique identifier for the object. */
    readonly id?: string;
    readonly payment_collection_date?: Date;
    /** Unique identifier for the payment gateway. */
    payment_gateway_id?: string;
    /** The date and time when the scheduled payment run is to be executed, in `yyyy-mm-dd hh:mm:ss` format. */
    payment_run_date?: Date;
    /** Human-readable identifier for this object. */
    payment_run_number?: string;
    /** Status of the payment run. */
    state?: PaymentRunState;
    /** The date and time when the payment run executed, in the `yyyy-mm-dd hh:mm:ss` format. */
    state_transitions?: PaymentRunStateTransitionsAllOf;
    /** Summary of the payment run. */
    readonly summary?: PaymentRunSummary;
    /** The target date used to determine which receivables to be paid in the payment run.       The payments are collected for all receivables with the due date no later than the target date. */
    target_date?: Date;
    /** Unique identifier of the Zuora user who last updated the object */
    readonly updated_by_id?: string;
    /** The date and time when the object was last updated in ISO 8601 UTC format. */
    readonly updated_time?: Date;
}
