/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Quickstart API Reference
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases.

To use the Quickstart API, you must have the following features enabled on your tenant:
 
* [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization)
* [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)

To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/).
We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.


 * OpenAPI spec version: 2024-01-24
 */
import type { PrepaidBalanceTransaction } from './prepaidBalanceTransaction';
/**
 */
export interface PrepaidBalance {
    /** End date of the fund effective period. */
    end_date?: Date;
    /** Unit of measure for the prepaid balance. */
    prepaid_UOM?: string;
    /** Remaining balance on the fund, which is the remaining units of the fund.  */
    remaining_balance?: number;
    /** Start date of the fund effective period. */
    start_date?: Date;
    /** The funded balance, which is the total units of the fund.  */
    total_balance?: number;
    /** An array of prepaid balance transactions */
    readonly transactions?: readonly PrepaidBalanceTransaction[];
}
