/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Quickstart API Reference
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases.

To use the Quickstart API, you must have the following features enabled on your tenant:
 
* [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization)
* [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)

To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/).
We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.


 * OpenAPI spec version: 2024-01-24
 */
import type { SubscriptionReplacePlanPatchRequestReplaceAt } from './subscriptionReplacePlanPatchRequestReplaceAt';
import type { SubscriptionReplacePlanPatchRequestReplacementType } from './subscriptionReplacePlanPatchRequestReplacementType';
import type { StartOn } from './startOn';
import type { SubscriptionPlanCreateRequest } from './subscriptionPlanCreateRequest';
export interface SubscriptionReplacePlanPatchRequest {
    /** Identifier of the plan to be removed. Only provide one of `previous_plan_id` or `subscription_plan_id` in your request, not both. */
    previous_plan_id?: string;
    /** The default value for the `replace_at` field is as follows:       <ul>         <li>If the subscription plan change (from old to new) is an upgrade, the `replace_at` is `now` by default. </li>         <li>If the subscription change (from old to new) is a downgrade, the `replace_at` is `end_of_billing_period` by default. </li>       </ul>       Otherwise, the `replace_at` is `specific_date` by default.            **Notes**:      <br />       When setting this field to `end_of_billing_period`, you cannot set the billing start dates for the subscription as the system will automatically set the start dates to the end of billing period, and you cannot set the following billing trigger date settings to `Yes`:      <ul>         <li> <a href="https://knowledgecenter.zuora.com/Zuora_Billing/Configure_billing_settings/Subscription_and_order_settings/A_Define_Default_Subscription_and_Order_Settings#Require_Customer_Acceptance_of_Orders.3F" target="_blank">Require Customer Acceptance of Orders</a> </li>         <li> <a href="https://knowledgecenter.zuora.com/Zuora_Billing/Billing_and_Invoicing/Billing_Settings/Define_Default_Subscription_and_Order_Settings#Require_Service_Activation_of_Orders.3F" target="_blank">Require Service Activation of Orders</a> </li>       </ul>       When setting this field to `specific_date`, you must also specify a date for the `contract_effective` date in the `start_on` field.      */
    replace_at?: SubscriptionReplacePlanPatchRequestReplaceAt;
    replacement_type?: SubscriptionReplacePlanPatchRequestReplacementType;
    start_on?: StartOn;
    subscription_plan: SubscriptionPlanCreateRequest;
    /** Identifier of the subscription plan. Only provide one of `previous_plan_id` or `subscription_plan_id` in your request, not both. */
    subscription_plan_id?: string;
}
