/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Quickstart API Reference
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases. 

To use the Quickstart API, you must have the following features enabled on your tenant:
 
* [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization) 
* [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)

To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/). 
We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.


 * OpenAPI spec version: 2024-01-24
 */
import type { AccountTaxCertificateState } from './accountTaxCertificateState';

/**
 * The tax certificate information.
 */
export type AccountTaxCertificate = {
  /** Unique code that identifies a company account in Avalara. Use this field to calculate taxes based on country of origin and sold-to addresses in Avalara. */
  company_code?: string;
  /** Description of the tax exemption certificate. */
  description?: string;
  /** The tax certificate end date. */
  end_date?: Date;
  /** A unique entity use code used by Avalara to apply exemptions. This field is required only when you choose Avalara as your tax engine. See [Exempt Transactions](https://developer.avalara.com/avatax/handling-tax-exempt-customers/) for more information. */
  entity_use_code?: string;
  /** Identifier of the tax exemption certificate. */
  id?: string;
  /** Typically, this is a state or government agency */
  issuing_jurisdiction?: string;
  /** The tax certificate start date. */
  start_date?: Date;
  /** Status of the tax exemption certificate, indication whether the certificate has been verified. */
  state?: AccountTaxCertificateState;
  /**
   * Value Added Tax (VAT) ID. Each VAT ID must begin with the code of the country code and followed by a block of digits or characters.
   * @deprecated
   */
  tax_identifier?: string;
};
