/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Quickstart API Reference
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases. 

To use the Quickstart API, you must have the following features enabled on your tenant:
 
* [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization) 
* [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)

To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/). 
We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.


 * OpenAPI spec version: 2024-01-24
 */
import type { CustomerAcceptanceMandate } from './customerAcceptanceMandate';
import type { CardMandateState } from './cardMandateState';
import type { CardMandateType } from './cardMandateType';

/**
 * A mandate is a record of the permission a customer has given you to debit their payment method. This hash contains details about the mandate.
 */
export interface CardMandate {
  /** A reference to the consent agreement you have with your customer. */
  readonly customer_acceptance?: CustomerAcceptanceMandate;
  /** Identifier of the single- or multi-use mandate generated by the payment gateway. */
  id?: string;
  /** Identifier of a network transaction. */
  readonly network_transaction_id?: string;
  /** Reason for the mandate. */
  reason?: string;
  /** The status of the mandate, which indicates whether it can be used to initiate a payment. */
  readonly state?: CardMandateState;
  /** Indicates the type of the stored credential profile, if any. */
  readonly type?: CardMandateType;
  /** Indicates the mandate was verified with the payment gateway by Zuora. */
  readonly verified?: boolean;
  /** Specifies if Zuora should verify this mandate. */
  verify?: boolean;
}
