/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Quickstart API Reference
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases. 

To use the Quickstart API, you must have the following features enabled on your tenant:
 
* [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization) 
* [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)

To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/). 
We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.


 * OpenAPI spec version: 2024-01-24
 */
import type { CustomFields } from './customFields';
import type { CreditMemoItemCreateRequest } from './creditMemoItemCreateRequest';

/**
 */
export interface CreditMemoCreateRequest {
  /** Identifier of the account that owns the credit memo.     **Either this field or `account_number` is required when creating credit memos from a price(charge in the v1 API).** */
  account_id?: string;
  /** Human-readable identifier of the account that owns the credit memo.    **Either this field or `account_id` is required when creating credit memos from a price(charge in the v1 API).** */
  account_number?: string;
  /** Whether to automatically apply the billing document upon posting. */
  apply?: boolean;
  /** 3-letter ISO 4217 currency code. This field is available only if you have the [Multiple Currencies](https://knowledgecenter.zuora.com/Zuora_Billing/Bill_your_customers/Flexible_Billing/Multiple_Currencies) feature enabled and are creating a credit memo from a charge. */
  currency?: string;
  custom_fields?: CustomFields;
  /** An arbitrary string associated with the object. Often useful for displaying to users. */
  description?: string;
  /** The date when the credit memo takes effect. */
  document_date?: Date;
  /** Indicates whether to exclude this credit memo from the rule of automatically applying it to invoices. */
  exclude_from_auto_apply_rules?: boolean;
  /** The identifier of the invoice billing document from which this credit memo is created.      **Required when creating credit memos from an invoice.** */
  invoice_id?: string;
  /** Information of all credit memo items. */
  items?: CreditMemoItemCreateRequest[];
  /** Whether to automatically post a billing document after it is created. */
  post?: boolean;
  /** Reason for issuing this credit memo */
  reason_code?: string;
  /** Whether to transfer to an external accounting system. */
  transfer_to_accounting?: boolean;
}
