/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Quickstart API Reference
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases. 

To use the Quickstart API, you must have the following features enabled on your tenant:
 
* [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization) 
* [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)

To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/). 
We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.


 * OpenAPI spec version: 2024-01-24
 */
import type { CreditMemoItemPreviewResponseProcessingType } from './creditMemoItemPreviewResponseProcessingType';

/**
 */
export interface CreditMemoItemPreviewResponse {
  /** The total amount of this credit memo item. */
  amount?: number;
  /** Identifier of an invoice item that this credit memo item is applied to. */
  applied_to_item_id?: string;
  /** Type of the charge. It can be one of the following types: one-time, recurring, or usage. */
  charge_type?: string;
  /** An arbitrary string associated with the object. Often useful for displaying to users. */
  description?: string;
  /** The date when the credit memo item takes effect. */
  document_item_date?: Date;
  document_item_number?: string;
  /** Unique identifier of the object */
  id?: string;
  processing_type?: CreditMemoItemPreviewResponseProcessingType;
  /** The number of units of this item. */
  quantity?: number;
  /** The end date of the service period associated with this credit memo item. If the associated charge is a one-time fee, then this date is the date of that charge. */
  service_end_date?: string;
  /** The start date of the service period associated with this credit memo item. If the associated charge is a one-time fee, then this date is the date of that charge. */
  service_start_date?: string;
  /** The unique SKU (stock keeping unit) of the product associated with this item. */
  sku?: string;
  /** The name of the SKU associated with this item */
  sku_name?: string;
  /** The identifier of the subscription associated with the credit memo item. */
  subscription_id?: string;
  /** The identifier the subscription item associated with this credit memo item. */
  subscription_item_id?: string;
  /** Human-readable identifier of the subscription. It can be user-supplied. */
  subscription_number?: string;
  /** The total amount of this credit memo item exclusive of tax. */
  subtotal?: number;
  /** Specifies the units used to measure usage. */
  unit_of_measure?: string;
}
