/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Quickstart API Reference
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases. 

To use the Quickstart API, you must have the following features enabled on your tenant:
 
* [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization) 
* [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)

To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/). 
We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.


 * OpenAPI spec version: 2024-01-24
 */
import type { Account } from './account';
import type { CreditMemoAppliedToResponse } from './creditMemoAppliedToResponse';
import type { Contact } from './contact';
import type { FlexibleBillingDocumentSettings } from './flexibleBillingDocumentSettings';
import type { CreditMemoCustomFields } from './creditMemoCustomFields';
import type { CreditMemoCustomObjects } from './creditMemoCustomObjects';
import type { CreditMemoItemListResponse } from './creditMemoItemListResponse';
import type { CreditMemoState } from './creditMemoState';
import type { CreditMemoStateTransitionsAllOf } from './creditMemoStateTransitionsAllOf';

/**
 */
export interface CreditMemo {
  /** The account that owns the billing document. EXPANDABLE */
  account?: Account;
  /** Identifier of the account that owns the credit memo.     **Either this field or `account_number` is required when creating credit memos from a price(charge in the v1 API).** */
  account_id?: string;
  /** Human-readable identifier of the account that owns the credit memo.    **Either this field or `account_id` is required when creating credit memos from a price(charge in the v1 API).** */
  account_number?: string;
  /** The amount this billing document refunded. */
  amount_refunded?: number;
  readonly applied_to?: readonly CreditMemoAppliedToResponse[];
  /**
   * The total balance remaining.  This field is deprecated. Use `remaining_balance` field.
   * @deprecated
   */
  readonly balance?: number;
  /** The billing address for the customer. */
  readonly bill_to?: Contact;
  /**
   * ID of the bill-to contact.
   * @nullable
   */
  bill_to_id?: string | null;
  /** The billing document settings for the customer. */
  billing_document_settings?: FlexibleBillingDocumentSettings;
  /** Unique identifier of the Zuora user who created the object */
  readonly created_by_id?: string;
  /** The date and time when the object was created in ISO 8601 UTC format. */
  readonly created_time?: Date;
  /** A human-readable identifier for the billing document; may be user-supplied. */
  readonly credit_memo_number?: string;
  /** 3-letter ISO 4217 currency code. This field is available only if you have the [Multiple Currencies](https://knowledgecenter.zuora.com/Zuora_Billing/Bill_your_customers/Flexible_Billing/Multiple_Currencies) feature enabled and are creating a credit memo from a charge. */
  currency?: string;
  /** Set of user-defined fields associated with this object. Useful for storing additional information about the object in a structured format. */
  custom_fields?: CreditMemoCustomFields;
  /** The custom objects associated with a Zuora standard object. */
  readonly custom_objects?: CreditMemoCustomObjects;
  /** An arbitrary string associated with the object. Often useful for displaying to users. */
  description?: string;
  /** The date when the credit memo takes effect. */
  document_date?: Date;
  /** Indicates whether to exclude this credit memo from the rule of automatically applying it to invoices. */
  exclude_from_auto_apply_rules?: boolean;
  /** Unique identifier for the object. */
  readonly id?: string;
  /** The identifier of the invoice billing document from which this credit memo is created.      **Required when creating credit memos from an invoice.** */
  invoice_id?: string;
  /** List of billing document items. EXPANDABLE */
  readonly items?: CreditMemoItemListResponse;
  /** Identifier of the Zuora user who posted the billing document. */
  readonly posted_by_id?: string;
  /** Reason for issuing this credit memo */
  reason_code?: string;
  /** The total balance remaining. */
  readonly remaining_balance?: number;
  /** The status of the billing document. */
  state?: CreditMemoState;
  state_transitions?: CreditMemoStateTransitionsAllOf;
  /** The total amount exclusive of tax. */
  readonly subtotal?: number;
  /** The total tax amount. */
  readonly tax?: number;
  /** The total amount. */
  readonly total?: number;
  /** Whether to transfer to an external accounting system. */
  transfer_to_accounting?: boolean;
  /** Unique identifier of the Zuora user who last updated the object */
  readonly updated_by_id?: string;
  /** The date and time when the object was last updated in ISO 8601 UTC format. */
  readonly updated_time?: Date;
}
