/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Quickstart API Reference
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases. 

To use the Quickstart API, you must have the following features enabled on your tenant:
 
* [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization) 
* [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)

To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/). 
We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.


 * OpenAPI spec version: 2024-01-24
 */
import type { SubscriptionAddPlanPatchResponse } from './subscriptionAddPlanPatchResponse';
import type { SubscriptionCancelPatchResponse } from './subscriptionCancelPatchResponse';
import type { SubscriptionPausePatchResponse } from './subscriptionPausePatchResponse';
import type { SubscriptionRemovePlanPatchResponse } from './subscriptionRemovePlanPatchResponse';
import type { SubscriptionRenewPatchResponse } from './subscriptionRenewPatchResponse';
import type { SubscriptionReplacePlanPatchResponse } from './subscriptionReplacePlanPatchResponse';
import type { SubscriptionResumePatchResponse } from './subscriptionResumePatchResponse';
import type { OrderActionStartOn } from './orderActionStartOn';
import type { SubscriptionPlanListResponse } from './subscriptionPlanListResponse';
import type { SubscriptionTermPatchResponse } from './subscriptionTermPatchResponse';
import type { OrderActionType } from './orderActionType';
import type { SubscriptionUpdatePlanPatchResponse } from './subscriptionUpdatePlanPatchResponse';

/**
 */
export interface OrderAction {
  /** Identifier of the action. */
  action_id?: string;
  /** Specify this field to add subscription plans to existing subscriptions. */
  add_subscription_plan?: SubscriptionAddPlanPatchResponse;
  /** Specify this field to cancel an existing subscription. */
  cancel?: SubscriptionCancelPatchResponse;
  /** Specify this field to pause an existing subscription. */
  pause?: SubscriptionPausePatchResponse;
  /** Specify this field to remove subscription plans from existing subscriptions. */
  remove_subscription_plan?: SubscriptionRemovePlanPatchResponse;
  /** Specify this field to renew an existing subscription. */
  renew?: SubscriptionRenewPatchResponse;
  /** Specify this field to replace existing subscription plans with new plans. */
  replace_subscription_plan?: SubscriptionReplacePlanPatchResponse;
  /** Specify this field to resume a paused subscription. */
  resume?: SubscriptionResumePatchResponse;
  /** The sequence number of the action. */
  sequence?: number;
  /** Indicates on which date the subscription becomes effective. */
  start_on?: OrderActionStartOn;
  /** Specify this field to add new plans to the new subscription. */
  subscription_plans?: SubscriptionPlanListResponse;
  terms?: SubscriptionTermPatchResponse;
  /** The action associated with this metric. */
  type?: OrderActionType;
  /** Specify this field to update subscription plans on the existing subscriptions. */
  update_subscription_plan?: SubscriptionUpdatePlanPatchResponse;
}
