/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Quickstart API Reference
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases. 

To use the Quickstart API, you must have the following features enabled on your tenant:
 
* [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization) 
* [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)

To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/). 
We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.


 * OpenAPI spec version: 2024-01-24
 */
import type { OrderLineItemBillingRule } from './orderLineItemBillingRule';
import type { OrderLineItemCategory } from './orderLineItemCategory';
import type { OrderLineItemCustomFields } from './orderLineItemCustomFields';
import type { OrderLineItemCustomObjects } from './orderLineItemCustomObjects';
import type { InvoiceItemListResponse } from './invoiceItemListResponse';
import type { OrderLineItemRevenueProperty } from './orderLineItemRevenueProperty';
import type { OrderLineItemState } from './orderLineItemState';
import type { OrderLineItemType } from './orderLineItemType';

/**
 * Data of order line items.
 */
export interface OrderLineItem {
  /** An active accounting code in your Zuora chart of accounts. */
  accounting_code?: string;
  /** An active accounting code in your Zuora chart of accounts. */
  adjustment_liability_account?: string;
  /** The billing rule for the order line item. */
  billing_rule?: OrderLineItemBillingRule;
  /** The category for the order line item, to indicate a product sale or return. */
  category?: OrderLineItemCategory;
  /** An active accounting code in your Zuora chart of accounts. */
  contract_asset_account?: string;
  /** An active accounting code in your Zuora chart of accounts. */
  contract_liability_account?: string;
  /** Unique identifier of the Zuora user who created the object */
  readonly created_by_id?: string;
  /** The date and time when the object was created in ISO 8601 UTC format. */
  readonly created_time?: Date;
  /** Set of user-defined fields associated with this object. Useful for storing additional information about the object in a structured format. */
  custom_fields?: OrderLineItemCustomFields;
  /** The custom objects associated with a Zuora standard object. */
  readonly custom_objects?: OrderLineItemCustomObjects;
  /** An arbitrary string attached to the object. Often useful for displaying to users. */
  description?: string;
  /** Discount percent. */
  discount_percent?: number;
  /** Total discount amount. */
  discount_total?: number;
  /** Discount amount per unit. */
  discount_unit_amount?: number;
  /** The date the order line item transitions to complete. */
  end_date?: Date;
  /** Unique identifier for the object. */
  readonly id?: string;
  /** List of invoice items. EXPANDABLE */
  readonly invoice_items?: InvoiceItemListResponse;
  /** Human-readable identifier of the order item. It can be user-supplied. */
  item_number?: string;
  /** The extended list price for an order line item, calculated by the formula: listPrice = listPricePerUnit * quantity */
  list_price?: number;
  /** The list price per unit for the order line item. */
  list_unit_price?: number;
  /** The name of the order line item. */
  name?: string;
  /** The unique identifier for the order associated with this order line item. */
  order_id?: string;
  /** The date when the subscription item is created through an order. This field is to standardize the booking date information to increase audit ability and traceability of data between Zuora Billing and Zuora Revenue. It is mapped as the booking date for a sales order line in Zuora Revenue. */
  original_order_date?: Date;
  /** The unique identifier of the original sales order for a return order line item. */
  original_order_id?: string;
  /** The unique identifier of the original sales order line item for a return order line item. */
  original_order_line_item_id?: string;
  /** The number of the original sales order line item for a return order line item. */
  original_order_line_item_number?: string;
  /** The number of the original sales order for a return order line item. */
  original_order_number?: string;
  /** The unique identifier of a contact belonging to the billing account of the order line item that was the original sold to contact when the order line item was created.  */
  original_sold_to_id?: string;
  /** Identifier of the price. */
  price_id?: string;
  /** The product code for the order line item. */
  product_code?: string;
  /** Used by customers to specify the Purchase Order Number provided by the buyer. */
  purchase_order_number?: string;
  /** The quantity of the product ordered. */
  quantity?: number;
  /** The quantity of the product ordered available for return. */
  quantity_available_for_return?: number;
  /** The quantity fulfilled. */
  quantity_fulfilled?: number;
  /** The quantity pending fulfillment. */
  quantity_pending_fulfillment?: number;
  /** Use this field to relate an order line item to an subscription. */
  related_subscription_number?: string;
  /** If true, a fulfillment is required to trigger billing. */
  requires_fulfillment?: boolean;
  /** Accounting configuration if you have Zuora Revenue enabled. */
  revenue?: OrderLineItemRevenueProperty;
  /** The unique identifier of a contact belonging to the billing account of the order line item. Use this field to assign and existing contact as the sold to contact of an order line item. */
  sold_to_id?: string;
  /** The date a transaction starts. The default value of this field is the order date. */
  start_date?: Date;
  /** The state of an order line item. If you want to generate billing documents for order line items, you must set this field to `sent_to_billing`. For invoice preview, you do not need to set this field. */
  state?: OrderLineItemState;
  /** Total before discounts and taxes are applied. */
  subtotal?: number;
  /** All order line items that were unbilled on or before this date are included in future bill runs. */
  target_date?: Date;
  /** The tax code for the order line item. */
  tax_code?: string;
  /** If this field is set to `true`, it indicates that amounts are inclusive of tax. */
  tax_inclusive?: boolean;
  /** Total after discounts and taxes. */
  total?: number;
  /** The type of the order line item. */
  type?: OrderLineItemType;
  /** An active accounting code in your Zuora chart of accounts.. */
  unbilled_receivables_account?: string;
  /** The unit amount to be charged. */
  unit_amount?: number;
  /** A configured unit of measure. */
  unit_of_measure?: string;
  /** Unique identifier of the Zuora user who last updated the object */
  readonly updated_by_id?: string;
  /** The date and time when the object was last updated in ISO 8601 UTC format. */
  readonly updated_time?: Date;
}
