/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Quickstart API Reference
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases. 

To use the Quickstart API, you must have the following features enabled on your tenant:
 
* [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization) 
* [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)

To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/). 
We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.


 * OpenAPI spec version: 2024-01-24
 */
import type { PaymentScheduleBillingDocumentResponse } from './paymentScheduleBillingDocumentResponse';
import type { PaymentScheduleCustomFields } from './paymentScheduleCustomFields';
import type { PaymentScheduleCustomObjects } from './paymentScheduleCustomObjects';
import type { PaymentScheduleItem } from './paymentScheduleItem';
import type { PaymentSchedulePaymentOptionRequest } from './paymentSchedulePaymentOptionRequest';
import type { PaymentSchedulePeriod } from './paymentSchedulePeriod';
import type { PaymentScheduleState } from './paymentScheduleState';

/**
 */
export interface PaymentSchedule {
  /** Unique identifier of the customer account the payment schedule belongs to. */
  account_id?: string;
  /** Account number of the customer account the payment schedule belongs to. */
  account_number?: string;
  /** The amount of each payment schedule item in the payment schedule. */
  amount?: number;
  /** The billing document with which the payment schedule is associated. Note: This field is optional. If you have the Standalone Payment feature enabled, you can leave this field blank and set standalone to true to create standalone payments. You can also choose to create unapplied payments by leaving this object blank and setting standalone to false. If Standalone Payment is not enabled, leaving this object unspecified will create unapplied payments. */
  billing_document?: PaymentScheduleBillingDocumentResponse;
  /** Unique identifier of the Zuora user who created the object */
  readonly created_by_id?: string;
  /** The date and time when the object was created in ISO 8601 UTC format. */
  readonly created_time?: Date;
  /** Currency of the payment schedule. Note: This field is optional. The default value is the account's default currency. This field will be ignored when items is specified. */
  currency?: string;
  /** If it is set to `true`, the payment schedule is a custom payment schedule. */
  custom?: boolean;
  /** Set of user-defined fields associated with this object. Useful for storing additional information about the object in a structured format. */
  custom_fields?: PaymentScheduleCustomFields;
  /** The custom objects associated with a Zuora standard object. */
  readonly custom_objects?: PaymentScheduleCustomObjects;
  /** An arbitrary string attached to the object. Often useful for displaying to users. */
  description?: string;
  /** Unique identifier for the object. */
  readonly id?: string;
  items?: PaymentScheduleItem[];
  /** The date of the next scheduled payment. */
  next_payment_date?: Date;
  /** The number of payment schedule items to be created for this payment schedule. */
  number_of_payments?: number;
  /** ID of the payment gateway used to collect payments. Note: This field is optional. The default value is the account's default payment gateway ID. If no payment gateway ID is found on the customer account level, the default value will be the tenant's default payment gateway ID. This field will be ignored when items is specified. */
  payment_gateway_id?: string;
  /** ID of the payment method. Note: This field is optional. The default value is the account's default payment method ID. This field will be ignored when items is specified. */
  payment_method_id?: string;
  /** Container for the payment options, which describe the transactional level rules for processing payments. Currently, only the gateway_options type is supported. Payment schedule payment_options take precedence over payment schedule item payment_options. */
  payment_options?: PaymentSchedulePaymentOptionRequest[];
  /** Number of the payment schedule. */
  payment_schedule_number?: string;
  /** Unit in which term duration is defined. One of week or month. */
  period?: PaymentSchedulePeriod;
  /** Indicates whether the payments created by the payment schedule will be used as reserved payments. This field will only be available if the prepaid cash drawdown permission is enabled. See <a href="https://knowledgecenter.zuora.com/Zuora_Billing/Bill_your_customers/Bill_for_usage_or_prepaid_products/Advanced_Consumption_Billing/Prepaid_with_Drawdown" target="_blank">Prepaid Cash with Drawdown for more information.</a> */
  prepayment?: boolean;
  /** The date of the most recent scheduled payment. */
  recent_payment_date?: Date;
  /**
   * At which hour in the day in the tenant's timezone this payment will be collected. Available values:[0,1,2,~,22,23]. If the time difference between your tenant’s timezone and the timezone where Zuora servers are located is not in full hours, for example, 2.5 hours, the payment schedule items will be triggered half an hour later than your scheduled time. The default value is 0. If the payment run_hour and scheduled_date are backdated, the system will collect the payment when the next run_hour occurs.
   * @minimum 0
   * @maximum 23
   */
  run_hour?: number;
  /** Indicates whether the payments created by the payment schedule are standalone payments or not.       
      When setting to `true`, standalone payments will be created.       When setting to `false`, you can either specify a billing document, or not specifying any billing documents.       In the latter case, unapplied payments will be created.       If set to `null`, standalone payments will be created.       
      **Note**: This parameter is only available if standalone payments are enabled in your tenant. The default value is `true` if standalone payments are enabled in your tenant. */
  standalone?: boolean;
  /** The date of the first scheduled payment collection. Note: This parameter is required when `items` is not specified. This parameter will be ignored when `items` is specified. */
  start_date?: Date;
  /** The status of the payment schedule. active: there are unprocessed payment schedule items. canceled: the payment schedule has been canceled. complete: the payment schedule is complete and all items have been processed. */
  state?: PaymentScheduleState;
  /** The total amount to be collected by the payment schedule. */
  total_amount?: number;
  /** The total number of failed payments. */
  total_payments_errored?: number;
  /** The total number of payments processed. */
  total_payments_processed?: number;
  /** Unique identifier of the Zuora user who last updated the object */
  readonly updated_by_id?: string;
  /** The date and time when the object was last updated in ISO 8601 UTC format. */
  readonly updated_time?: Date;
}
