/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import type { Pet } from './pet';
/**
 * @minItems 1
 * @maxItems 20
 */
export type Pets = Pet[];
//# sourceMappingURL=pets.d.ts.map
