/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Quickstart API Reference
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases. 

To use the Quickstart API, you must have the following features enabled on your tenant:
 
* [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization) 
* [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)

To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/). 
We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.


 * OpenAPI spec version: 2024-01-24
 */
import type { QueryRunCreateRequestContentEncoding } from './queryRunCreateRequestContentEncoding';
import type { QueryRunCreateRequestContentType } from './queryRunCreateRequestContentType';

export interface QueryRunCreateRequest {
  /** The character used as delimiter to separate values in the output file. */
  column_separator?: string;
  /** If supplied, Zuora with compress the output file using the specified compression algorithm. */
  content_encoding?: QueryRunCreateRequestContentEncoding;
  /** The type of the file returned. */
  content_type: QueryRunCreateRequestContentType;
  /** Base64-encoded public key of a 1024-bit RSA key-pair. If you set this field, Zuora will encrypt the query results using the provided public key. You must use the corresponding private key to decrypt the query results. */
  encryption_key?: string;
  /** If set to `true`, any deleted records are included in the response. */
  read_deleted?: boolean;
  /** The SQL statement of the query. */
  sql: string;
}
