/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Quickstart API Reference
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases. 

To use the Quickstart API, you must have the following features enabled on your tenant:
 
* [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization) 
* [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)

To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/). 
We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.


 * OpenAPI spec version: 2024-01-24
 */
import type { Account } from './account';
import type { RefundsAppliedToResponse } from './refundsAppliedToResponse';
import type { RefundCreditMemoRequest } from './refundCreditMemoRequest';
import type { RefundCustomFields } from './refundCustomFields';
import type { RefundCustomObjects } from './refundCustomObjects';
import type { RefundGatewayOptions } from './refundGatewayOptions';
import type { RefundGatewayState } from './refundGatewayState';
import type { RefundPaymentMethod } from './refundPaymentMethod';
import type { RefundRefundMethodType } from './refundRefundMethodType';
import type { RefundState } from './refundState';
import type { RefundStateTransitionsProperty } from './refundStateTransitionsProperty';

/**
 */
export interface Refund {
  /** The account that owns the refund */
  account?: Account;
  /** Identifier of the customer this refund is for, if one exists. */
  account_id?: string;
  /** Refund amount. */
  amount?: number;
  readonly applied_to?: readonly RefundsAppliedToResponse[];
  /** An active account in your Zuora Chart of Accounts. */
  bank_account_account?: string;
  /** Comments about the refund. */
  comment?: string;
  /** Unique identifier of the Zuora user who created the object */
  readonly created_by_id?: string;
  /** The date and time when the object was created in ISO 8601 UTC format. */
  readonly created_time?: Date;
  /** The related credit memo. */
  credit_memo?: RefundCreditMemoRequest;
  /** Set of user-defined fields associated with this object. Useful for storing additional information about the object in a structured format. */
  custom_fields?: RefundCustomFields;
  /** The custom objects associated with a Zuora standard object. */
  readonly custom_objects?: RefundCustomObjects;
  /** An arbitrary string attached to the object. Often useful for displaying to users. */
  description?: string;
  /** If true, indicates that this refund is not handled by Zuora. */
  external?: boolean;
  /** Identifier of the payment gateway that Zuora will use to authorize the payments that are made with this payment method. If you do not set this field, Zuora will use one of the following payment gateways instead: The default payment gateway of the customer account that owns the payment method, if the payment method is associated with a customer account or the default payment gateway of your Zuora tenant. */
  gateway_id?: string;
  gateway_options?: RefundGatewayOptions;
  /** Gateway reconciliation reason. */
  readonly gateway_reconciliation_reason?: string;
  /** Gateway reconciliation state. */
  readonly gateway_reconciliation_status?: string;
  /** Message returned by the payment gateway for this refund. */
  readonly gateway_response?: string;
  /** Code returned by the payment gateway for this refund. */
  readonly gateway_response_code?: string;
  /** The payment gateway state of the refund. */
  readonly gateway_state?: RefundGatewayState;
  id?: string;
  /** An active account in your Zuora Chart of Accounts. */
  on_account_account?: string;
  /** Identifier for the payment, either `payment_number` or `payment_id. */
  readonly payment_id?: string;
  /** Payment method information. */
  payment_method?: RefundPaymentMethod;
  /** Identifier of the payment method used to create this refund. */
  readonly payment_method_id?: string;
  /** Identifier of the payout from the payment gateway. */
  readonly payout_id?: string;
  /** User-provided reason for the refund. */
  reason_code?: string;
  /** Transaction identifier returned by the payment gateway. You may use this field to reconcile refunds between your payment gateway and Zuora Payments. */
  reference_id?: string;
  /** The date when the refund takes effect. */
  refund_date?: Date;
  refund_method_type?: RefundRefundMethodType;
  /** Human-readable identifier for this object; may be user-supplied. */
  refund_number?: string;
  /** A second transaction identifier returned by the payment gateway if there is an additional transaction for the refunds. You may use this field to reconcile payments between your payment gateway and Zuora Payments. */
  second_reference_id?: string;
  /** The state of the refund. */
  readonly state?: RefundState;
  /** The timestamps at which the object's state was updated. */
  state_transitions?: RefundStateTransitionsProperty;
  /** A payment gateway-specific field used by Orbital, Vantiv and Verifi. */
  statement_descriptor?: string;
  /** A payment gateway-specific field used by Orbital, Vantiv and Verifi. */
  statement_descriptor_phone?: string;
  /** An active account in your Zuora Chart of Accounts. */
  unapplied_payment_account?: string;
  /** Unique identifier of the Zuora user who last updated the object */
  readonly updated_by_id?: string;
  /** The date and time when the object was last updated in ISO 8601 UTC format. */
  readonly updated_time?: Date;
}
