/**
 * Generated by orval v6.27.1 🍺
 * Do not edit manually.
 * Quickstart API Reference
 * Zuora Quickstart API is recommended for new customers and integrators, allowing new integrators to swiftly integrate with Zuora. It supports essential business use cases. 

To use the Quickstart API, you must have the following features enabled on your tenant:
 
* [Orders](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders) or [Orders Harmonization](https://knowledgecenter.zuora.com/Billing/Subscriptions/Orders/Orders_Harmonization) 
* [Invoice Settlement](https://knowledgecenter.zuora.com/Billing/Billing_and_Payments/Invoice_Settlement)

To find the latest changes made to the Zuora Quickstart API, check the [Quickstart API Changelog](https://developer.zuora.com/quickstart-api/changelog/2022q4-changelog/). 
We recommend that you subscribe to [Developers Community](https://community.zuora.com/communities/community-home?communitykey=e2a932b4-50c4-4019-a3e8-362e38714df3) to get notifications when a new version is released.


 * OpenAPI spec version: 2024-01-24
 */
import type { SubscriptionItemPatchRequestApplyDiscountToItem } from './subscriptionItemPatchRequestApplyDiscountToItem';
import type { CustomFields } from './customFields';
import type { SubscriptionItemPatchRequestDiscountLevel } from './subscriptionItemPatchRequestDiscountLevel';
import type { Overage } from './overage';
import type { SubscriptionItemPrepaymentField } from './subscriptionItemPrepaymentField';
import type { Recurring } from './recurring';
import type { SubscriptionItemPatchRequestStartEvent } from './subscriptionItemPatchRequestStartEvent';
import type { ItemTier } from './itemTier';

/**
 */
export interface SubscriptionItemPatchRequest {
  /** The amount of the price. Specify this field if you want to override the original price with a flat-fee price */
  amount?: number;
  /** Any combination of one-time, recurring, or usage prices. */
  apply_discount_to?: SubscriptionItemPatchRequestApplyDiscountToItem[];
  /** Name of the custom field that will be used to set a per unit rate under the `Pre-Rated Per Unit` charge model  */
  custom_field_per_unit_rate?: string;
  /** Name of the custom field that will be used to set a total amount under the `Pre-Rated` charge model  */
  custom_field_total_amount?: string;
  custom_fields?: CustomFields;
  /** An arbitrary string attached to the object. Often useful for displaying to users. */
  description?: string;
  /** Specifies at what level a discount should be applied. */
  discount_level?: SubscriptionItemPatchRequestDiscountLevel;
  /** Discount percent. Specify this field if you want to override with a discount-based discount price. */
  discount_percent?: number;
  /** The date when the subscription item ends or ended. */
  end_date?: Date;
  /** Identifier of the subscription item. */
  id?: string;
  overage?: Overage;
  prepayment?: SubscriptionItemPrepaymentField;
  /** Quantity of the product to which your customers subscribe. */
  quantity?: number;
  recurring?: Recurring;
  /** The date when the subscription item starts */
  start_date?: Date;
  /** Specifies when to start billing your customer. */
  start_event?: SubscriptionItemPatchRequestStartEvent;
  /** Human-readable identifier of the subscription. It can be user-supplied. */
  subscription_item_number?: string;
  /** Information of all tiers if you want to override the original price with a tiered price. */
  tiers?: ItemTier[];
  /** Unique identifier for the price. This identifier enables you to refer to the price before the price has an internal identifier in Zuora. */
  unique_token?: string;
  /** The unit amount of the price. Specify this field if you want to override the orignial price with a per-unit price. */
  unit_amount?: number;
}
